server.port: 8080
# profiles和yml的---区分多文件，对不同的application的进行环境区分
spring:
  profiles:
    active: demo
---
########################demo使用的数据库#####################
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mysql/demo/*.xml

spring:
  profiles: demo
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/localtest?serverTimezone=GMT%2B8
    useSSL: false
    username: root
    password: hntywork
server:
  port: 8081
#logging:
#  level: debug
########################END demo使用的数据库#####################
---
#########################quartz使用的数据库#####################
spring:
  profiles: quartz
  datasource:
    url: jdbc:mysql://localhost:3306/quartz?serverTimezone=GMT%2B8
    username: root
    password: hntywork
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations:
    - classpath:mysql/quartz/*.xml
  type-aliases-package: com.example.quartz_one.entity
  config-location: classpath:mybaits-config.xml

server:
  port: 8081

#########################END quartz使用的数据库#####################
---
#########################KAFKA 使用的数据库#####################
spring:
  profiles: kafka
  datasource:
    url: jdbc:mysql://localhost:3306/quartz?serverTimezone=GMT%2B8
    username: root
    password: hntywork
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: 192.168.239.128:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: test
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


mybatis:
  mapper-locations:
    - classpath:mysql/quartz/*.xml
  type-aliases-package: com.example.quartz_one.entity
  config-location: classpath:mybaits-config.xml

server:
  port: 8081



#########################END KAFKA 使用的数据库#####################
---
