server.port: 8080
# profiles和yml的---区分多文件，对不同的application的进行环境区分
spring:
  profiles:
    active: quartz
---
########################demo使用的数据库#####################
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mysql/demo/*.xml

spring:
  profiles: demo
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/localtest?serverTimezone=GMT%2B8
    useSSL: false
    username: root
    password: hntywork
########################END demo使用的数据库#####################
server:
  port: 8001
#logging:
#  level: debug
---
#########################quartz使用的数据库#####################
spring:
  profiles: quartz
  datasource:
    url: jdbc:mysql://localhost:3306/quartz?serverTimezone=GMT%2B8
    username: root
    password: hntywork
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations:
    - classpath:mysql/quartz/*.xml
  type-aliases-package: com.example.quartz_one.entity

server:
  port: 9065

#########################END quartz使用的数据库#####################
---
#quartz:
#  scheduler:
#    instanceName: MyselfScheduler
#    instanceId: Auto
#    instance-id: NON_CLUSTERED # 使用集群：AUTO 不使用集群：NON_CLUSTERED
#    skip-update-check: true
#    job-factory:
#      class: org.quartz.simpl.SimpleJobFactory
#  job-store:
#    class: org.quartz.impl.jdbcjobstore.JobStoreTX
#    driver-delegate-class: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#    datasource: quartzDataSource
#    table-prefix: QRTZ_
#    is-clustered: true
#  thread-pool:
#    class: org.quartz.simpl.SimpleThreadPool
#    thread-count: 5
#    threadPriority: 5
#    threadsInheritContextClassLoaderOfInitializingThread: true
#  dataSource:
#    quartzDataSource:
#      driver:
#      url: ${spring.datasource.druid.url}
#      user: ${spring.datasource.druid.username}
#      password: ${spring.datasource.druid.password}
#      maxConnections: 5
#      validationQuery: select 0
#      connection-provider:
#        class: com.lingdu.welend.config.quartz.DruidConnectionProvider
#  job-store-type: jdbc

#  quartz:
#    #相关属性配置
#    properties:
#      org:
#        quartz:
#          #Configure Main Scheduler Properties     调度器属性
#          scheduler:
#            instanceName: clusteredScheduler
#            instanceId: AUTO
#          dataSource:
#              driver : com.mysql.jdbc.Driver
#              URL : jdbc:mysql://localhost:3306/quartz?autoReconnect=true&characterEncoding=utf-8&useSSL=false
#              user : root
#              password : hntywork
#              maxConnections : 10
#              validationQuery: select 0
#          #Configure JobStore 作业存储设置
#          jobStore:
#            #              class: org.quartz.simpl.RAMJobStore
#            class: org.quartz.impl.jdbcjobstore.JobStoreTX
#            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
#            tablePrefix: QRTZ_
#            isClustered: true
#            clusterCheckinInterval: 10000
#            useProperties: false
#          #Configure ThreadPool     线程池属性
#          threadPool:
#            class: org.quartz.simpl.SimpleThreadPool
#            threadCount: 20
#            threadPriority: 5
#            threadsInheritContextClassLoaderOfInitializingThread: true
#      #数据库方式
#      job-store-type: jdbc